// Nyiakeng Puachue Mhong characters with their images
export const nyiakengDict: Record<string, string> = {
  // CONSONANTS
    "𞄀": "src/images/cat.png",
    "𞄁": "src/images/tiger.png",
    "𞄂": "src/images/ladder.png",
    "𞄃": "src/images/buffalo.png",
    "𞄄": "src/images/cloud.png",
    "𞄅": "src/images/squirrel.png",
    "𞄆": "src/images/thread.png",
    "𞄇": "src/images/boat.png",
    "𞄈": "src/images/orangutan.png",
    "𞄉": "src/images/rabbit.png",
    "𞄊": "src/images/necklace.png",
    "𞄋": "src/images/cabbage.png",
    "𞄌": "src/images/mushroom.png",
    "𞄍": "src/images/fish.png",
    "𞄎": "src/images/umbrella.png",
    "𞄏": "src/images/spoon.png",
    "𞄐": "src/images/cow.png",
    "𞄑": "src/images/drums.png",
    "𞄒": "src/images/turtle.png",
    "𞄓": "src/images/elephant.png",
    "𞄔": "src/images/scissor.png",
    "𞄕": "src/images/glass.png",
    "𞄖": "src/images/mountain.png",
    "𞄗": "src/images/chicken.png",
    "𞄘": "src/images/sheep.png",
    "𞄙": "src/images/dove.png",
    "𞄚": "src/images/flower.png",
    "𞄛": "src/images/bamboo.png",
    "𞄜": "src/images/soccer.png",
    "𞄝": "src/images/waterfall.png",
    "𞄞": "src/images/earth.png",
    "𞄟": "src/images/ahhh.png",
    "𞄠": "src/images/idols.png",
    "𞄡": "src/images/owl.png",
    "𞄢": "src/images/meow.png",
    "𞄣": "src/images/rainbow.png",
};